use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :mariechen, MariechenWeb.Endpoint,
  http: [:inet6, port: System.get_env("PORT") || 4006],
  url: [host: "www.mariechen.com", path: "/ex"],
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: ["https://shop.mariechen.com", "https://www.mariechen.com"]

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :mariechen, MariechenWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         :inet6,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :mariechen, MariechenWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases (distillery)
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :mariechen, MariechenWeb.Endpoint, server: true
#
# Note you can't rely on `System.get_env/1` when using releases.
# See the releases documentation accordingly.

# Finally import the config/prod.secret.exs which should be versioned
# separately.

config :mariechen, :config,
  local_url: "https://mariechen.werkzeugh.at",
  invoice_url: "/ex/pdfs",
  shop_bcc_recipients: ["werkzeugh@gmail.com"]
  integration_tpl_url: "/products/limited-edition/ex_template?no_cache=1"

config :kandis,
  invoice_dir: "/www/mariechen_ex/pdfs",
  local_url: "https://mariechen.werkzeugh.at"

config :kandis, :sofort,
  local_url: "https://mariechen.werkzeugh.at",
  client_nr: "124988",
  project_id: "590216",
  base_url: "https://api.sofort.com/api/xml"

config :mariechen, Mariechen.Scheduler,
  jobs: [
    {"03,33 * * * *", {Mariechen.Core.Stock, :write_stock_data, []}},
    {"* * * * *", {Kandis.Order, :cancel_expired_orders, []}}
  ]

import_config "prod.secret.exs"
